/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author José Pinto A81317
 * @author Luís Correia A81141
 * @author Pedro Barbosa A82068
 */
public class CriarConfigView extends javax.swing.JDialog {

    private ConfiguraFacil configuraFacil;
    
    /**
     * Creates new form CriarConfigView
     */
    public CriarConfigView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public CriarConfigView(ConfiguraFacil config){
        setTitle("Opções Obrigatórias");
        initComponents();
        this.configuraFacil = config;
        
        DefaultListModel<ListOb> mod = new DefaultListModel<ListOb>();
        DefaultListModel<ListOb> mot = new DefaultListModel<ListOb>();
        DefaultListModel<ListOb> pin = new DefaultListModel<ListOb>();
        DefaultListModel<ListOb> est = new DefaultListModel<ListOb>();
        DefaultListModel<ListOb> jan = new DefaultListModel<ListOb>();



        List<Obrigatorio> obrigatorios = this.configuraFacil.getObrigatorios();
        
        for(Obrigatorio o : obrigatorios){
            if(o.getCategoria().equals("Modelo")){
                mod.addElement(new ListOb(o.getId(), o.getDesignacao(), o.getPreco()));
            }
            else if(o.getCategoria().equals("Motor")){
                mot.addElement(new ListOb(o.getId(), o.getDesignacao(), o.getPreco()));
            }
            else if(o.getCategoria().equals("Pintura")){
                pin.addElement(new ListOb(o.getId(), o.getDesignacao(), o.getPreco()));
            }
            else if(o.getCategoria().equals("Estofos")){
                est.addElement(new ListOb(o.getId(), o.getDesignacao(), o.getPreco()));
            }
            else if(o.getCategoria().equals("Jantes")){
                jan.addElement(new ListOb(o.getId(), o.getDesignacao(), o.getPreco()));
            }
        }
        
        modelo.setModel(mod);      
        motor.setModel(mot);
        pintura.setModel(pin);
        estofos.setModel(est);
        jantes.setModel(jan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        seguinte = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelo = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        motor = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        pintura = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        estofos = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jantes = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        preco = new javax.swing.JTextPane();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Modelo");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Motor");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Pintura");

        seguinte.setText("Seguinte");
        seguinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguinteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Estofos");

        modelo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                modeloValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(modelo);

        jScrollPane2.setViewportView(motor);

        jScrollPane3.setViewportView(pintura);

        jScrollPane4.setViewportView(estofos);

        jScrollPane5.setViewportView(jantes);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Jantes");

        jScrollPane6.setViewportView(preco);

        label1.setText("label1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(126, 126, 126)
                .addComponent(jLabel2)
                .addGap(150, 150, 150)
                .addComponent(jLabel3)
                .addGap(175, 175, 175)
                .addComponent(jLabel5)
                .addGap(249, 249, 249)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seguinte)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seguinte)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seguinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguinteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seguinteActionPerformed

    private void modeloValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_modeloValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloValueChanged

    public void seguinteListener (ActionListener al) {
        seguinte.addActionListener(al);
    }
    
    public void modeloListener (ListSelectionListener lsl) {
        modelo.addListSelectionListener(lsl);
    }
    
    public void motorListener (ListSelectionListener lsl) {
        motor.addListSelectionListener(lsl);
    }
    
    public void pinturaListener (ListSelectionListener lsl) {
        pintura.addListSelectionListener(lsl);
    }
    
    public void estofosListener (ListSelectionListener lsl) {
        estofos.addListSelectionListener(lsl);
    }
    
    public void jantesListener (ListSelectionListener lsl) {
        jantes.addListSelectionListener(lsl);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarConfigView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarConfigView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarConfigView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarConfigView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CriarConfigView dialog = new CriarConfigView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<ListOb> estofos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList<ListOb> jantes;
    private java.awt.Label label1;
    private javax.swing.JList<ListOb> modelo;
    private javax.swing.JList<ListOb> motor;
    private javax.swing.JList<ListOb> pintura;
    private javax.swing.JTextPane preco;
    private javax.swing.JButton seguinte;
    // End of variables declaration//GEN-END:variables

    public float getPrecoLista(JList<ListOb> lista){
        ListOb o = lista.getSelectedValue();
        if(o != null) { 
            return o.getPreco();
        }
        else
            return 0;
    }
    
    public int getModelo(){
        return modelo.getSelectedValue().getId();
    }
    
    public int getMotor(){
        return motor.getSelectedValue().getId();
    }
    
    public int getPintura(){
        return pintura.getSelectedValue().getId();
    }
    
    
    public int getEstofos(){
        return estofos.getSelectedValue().getId();
    }
    
    public int getJantes(){
        return jantes.getSelectedValue().getId();
    }    
    
    public boolean areAllSelected(){
        return !modelo.isSelectionEmpty() && 
               !motor.isSelectionEmpty() &&
               !pintura.isSelectionEmpty() &&
               !estofos.isSelectionEmpty() &&
               !jantes.isSelectionEmpty();
    }

    void atualizaPreco() {
        float p = getPrecoLista(modelo) + getPrecoLista(motor) + getPrecoLista(pintura) + getPrecoLista(estofos) + getPrecoLista(jantes);
        preco.setText("" + p);
    }
}

class ListOb{
    private int id;
    private String designacao;
    private float preco;
    
    public ListOb(int id, String d, float preco){
        this.id = id;
        this.designacao = d;
        this.preco = preco;
    }
    
    public String toString(){
        return this.designacao + "        " + this.preco + "€";
    }
    
    public int getId(){
        return this.id;
    }

    public float getPreco() {
        return preco;
    }
}